# Enable Base USB and BLE
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Bluetooth Name (Must be <= 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="MSI GL62M"

# Disable CDC USB Logging (Prevents UART/CDC Kconfig errors)
CONFIG_ZMK_USB_LOGGING=n

# Required for Pico W CYW43 Bluetooth Controller
CONFIG_BT=y
CONFIG_BT_CTLR=n
CONFIG_BT_HCI=y
