# Basic USB and BLE Configuration
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Shortened Bluetooth name to stay under the 16-character limit
CONFIG_ZMK_KEYBOARD_NAME="MSI GL62M"

# Disable logging to prevent CDC ACM hardware crashes
CONFIG_ZMK_USB_LOGGING=n
